# Deployment
deployment:
    # precise the number of replicas
    replicas: 1
    # precise the container image used for this chart
    container:
      image: supinfo4kube/api-gateway:1.0.1
    # precise the environment to use 
    env:
      enabled: true
      name: SPRING_PROFILES_ACTIVE
      value: production-microservice
    # precise the ports that we used
    ports:
      first-port: 
        containerPort: 8080
      
    # it's about the ressources that can be used for this deployment
    ressources:
      enabled: true
      requests:
        memory: "256Mi"
        cpu: "20m"  
      limits:
        memory: "512Mi"
        cpu: "50m"
    # Volume Mount
    volumeMount:
      enabled: false
    # Volume
    volume:
      enabled: false

# Service
service:
  # precise the differents ports to use for the application
  ports:
    first-port:
      name: http
      port: 8080
      targetPort: 8080

namespace: fleetman