---
# Source: ChartAll/charts/namespace/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fleetman
---
# Source: ChartAll/charts/fleetman-mongodb/templates/persistentVolume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetman-mongodb
spec:
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  capacity :
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
      path: "/mnt/data"
---
# Source: ChartAll/charts/fleetman-mongodb/templates/persistentVolumeClaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleetman-mongodb
  labels :
    app: fleetman-mongodb
  namespace: fleetman
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
# Source: ChartAll/charts/fleetman-api-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  namespace: fleetman
spec:
  selector:
    app: fleetman-api-gateway
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Source: ChartAll/charts/fleetman-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  namespace: fleetman
spec:
  selector:
    app: fleetman-mongodb
  ports:
    - protocol: TCP
      name: http
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
# Source: ChartAll/charts/fleetman-position-simulator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  namespace: fleetman
spec:
  selector:
    app: fleetman-position-simulator
  ports:
    - protocol: TCP
      name: http
      port: 30020
      targetPort: 8080
  type: ClusterIP
---
# Source: ChartAll/charts/fleetman-position-tracker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  namespace: fleetman
spec:
  selector:
    app: fleetman-position-tracker
  ports:
    - protocol: TCP
      name: first-port
      port: 30010
      targetPort: 8080
  type: ClusterIP
---
# Source: ChartAll/charts/fleetman-queue/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: fleetman
spec:
  selector:
    app: fleetman-queue
  ports:
    - protocol: TCP
      name: first-port
      port: 8161
      targetPort: 8161
    - protocol: TCP
      name: second-port
      port: 61616
      targetPort: 61616
  type: ClusterIP
---
# Source: ChartAll/charts/fleetman-webapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  namespace: fleetman
spec:
  selector:
    app: fleetman-webapp
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
---
# Source: ChartAll/charts/fleetman-api-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
  namespace: fleetman
  labels:
    app: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
        - name: fleetman-api-gateway
          image: supinfo4kube/api-gateway:1.0.1         
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
---
# Source: ChartAll/charts/fleetman-mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
  namespace: fleetman
  labels:
    app: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
        - name: fleetman-mongodb
          image: mongo:3.6.23         
          ports:
          - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: fleetman-mongodb
---
# Source: ChartAll/charts/fleetman-position-simulator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
  namespace: fleetman
  labels:
    app: fleetman-position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
        - name: fleetman-position-simulator
          image: supinfo4kube/position-simulator:1.0.1         
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
---
# Source: ChartAll/charts/fleetman-position-tracker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker
  namespace: fleetman
  labels:
    app: fleetman-position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
        - name: fleetman-position-tracker
          image: supinfo4kube/position-tracker:1.0.1         
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
---
# Source: ChartAll/charts/fleetman-queue/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  namespace: fleetman
  labels:
    app: fleetman-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - name: fleetman-queue
          image: supinfo4kube/queue:1.0.1         
          ports:
          - containerPort: 8161
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
---
# Source: ChartAll/charts/fleetman-webapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
  namespace: fleetman
  labels:
    app: fleetman-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-webapp
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
        - name: fleetman-webapp
          image: supinfo4kube/web-app:1.1.0-dockercompose         
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
