---
# Source: fleetman-position-simulator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator-release-name
  namespace: 
spec:
  selector:
    app: fleetman-position-simulator
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Source: fleetman-position-simulator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator-release-name
  namespace: 
  labels:
    app: fleetman-position-simulator-release-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
        - name: fleetman-position-simulator
          image: richardchesterwood/k8s-fleetman-position-simulator:release2
          
          # Définition de mes dict pour éviter accès à la nil (éviter les erreurs)
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
7