# Deployment
deployment:
    # Set the replicas number
    replicas: 2
    # precise the container image used for this chart
    container:
      image: richardchesterwood/k8s-fleetman-position-simulator:release2
    # precise the environment to use 
    env:
      enabled: true
      name: SPRING_PROFILES_ACTIVE
      value: local-microservice
    ports:
      first-port:
        containerPort: 5010
        targetPort: 5010
    # it's about the ressources that can be used for this deployment
    ressources:
      enabled: true
      requests:
        memory: "256Mi"
        cpu: "20m"  
      limits:
        memory: "512Mi"
        cpu: "50m"
    volumeMount:
      enabled: false
    volume:
      enabeld: false
      

# Service
service:
  # precise the differents ports to use for the application
  ports:
    first-port:
      name: http
      port: 8080
      targetPort: 8080

namespace: fleetman