# Deployment
deployment:
    # Set the replicas number
    replicas: 2
    # precise the container image used for this chart
    container:
      image: mongo:3.6.23
    # precise the environment to use 
    env:
      enabled: false
    # it's about the ressources that can be used for this deployment
    ressources:
      enabled: true
      requests:
        memory: "256Mi"
        cpu: "20m"  
      limits:
        memory: "512Mi"
        cpu: "50m"
    
    ports:
      first-port:
        containerPort: 27019
        targetPort: 27019

# Service
service:
  # precise the differents ports to use for the application
  ports:
    first-port:
      name: http
      port: 27017
      targetPort: 27017

namespace: fleetman