# Deployment
deployment:
    # Set the replicas number
    replicas: 1
    # precise the container image used for this chart
    container:
      image: supinfo4kube/queue:1.0.1  
    # precise the environment to use 
    env:
      enabled: false
    # precise the ports to use
    ports:
      first-port: 
        containerPort: 8161
    # it's about the ressources that can be used for this deployment
    ressources:
      enabled: true
      requests:
        memory: "256Mi"
        cpu: "20m"  
      limits:
        memory: "512Mi"
        cpu: "50m"
    volumeMount:
      enabled: false
    volume:
      enabeld: false

# Service
service:
  # precise the differents ports to use for the application
  ports:
    first-port:
      name: first-port
      port: 8161
      targetPort: 8161
    second-port:
      name: second-port
      port: 61616
      targetPort: 61616

namespace: fleetman