# Deployment
deployment:
    # Set the replicas number
    replicas: 1
    # precise the container image used for this chart
    container:
      image: supinfo4kube/web-app:1.1.0-dockercompose
    # precise the environment to use 
    env:
      enabled: false
    ports:
      first-port: 
        containerPort: 80
    # it's about the ressources that can be used for this deployment
    ressources:
      enabled: true
      requests:
        memory: "256Mi"
        cpu: "20m"  
      limits:
        memory: "512Mi"
        cpu: "50m"
    volumeMount:
      enabled: false
    volume:
      enabeld: false
      

# Service
service:
  # precise the differents ports to use for the application
  ports:
    first-port:
      name: http
      port: 80
      targetPort: 30080
  
  type: NodePort

namespace: fleetman