---
# Source: fleetman-position-tracker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker-release-name
  namespace: 
spec:
  selector:
    app: fleetman-position-tracker
  ports:
    - protocol: TCP
      name: http
      port: 30010
      targetPort: 8080
  type: ClusterIP
---
# Source: fleetman-position-tracker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker-release-name
  namespace: 
  labels:
    app: fleetman-position-tracker-release-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
        - name: fleetman-position-tracker
          image: supinfo4kube/position-tracker:1.0.1
          
          # Définition de mes dict pour éviter accès à la nil (éviter les erreurs)
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
