---
# Source: fleetman-position-tracker/templates/persistentVolume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleetman-position-tracker-release-name
  labels :
    app: fleetman-position-tracker-release-name
  namespace: fleetman
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: 
  resources:
    requests:
      storage: 1Gi
---
# Source: fleetman-position-tracker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker-release-name
  namespace: fleetman
spec:
  selector:
    app: fleetman-position-tracker
  ports:
    - protocol: TCP
      name: first-port
      port: 8161
      targetPort: 8161
    - protocol: TCP
      name: second-port
      port: 61616
      targetPort: 61616
  type: ClusterIP
---
# Source: fleetman-position-tracker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker-release-name
  namespace: fleetman
  labels:
    app: fleetman-position-tracker-release-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
        - name: fleetman-position-tracker
          image: supinfo4kube/position-tracker:1.0.1         
          ports:
          - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          volumeMounts:
            - name: position-tracker-data
              mountPath: /data/position-tracker
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
      volumes:
        - name: position-tracker-data
          persistentVolumeClaim:
            claimName: fleetman-position-tracker-release-name
