# Deployment
deployment:
    # Set the replicas number
    replicas: 1
    # precise the container / image used for this chart
    container:
      image: supinfo4kube/position-tracker:1.0.1
    # precise the environment to use 
    env:
      enabled: true
      name: SPRING_PROFILES_ACTIVE
      value: production-microservice
    # precise the ports to use
    ports:
      first-port: 
        containerPort: 8080
    # it's about the ressources that can be used for this deployment
    ressources:
      enabled: true
      requests:
        memory: "256Mi"
        cpu: "20m"  
      limits:
        memory: "512Mi"
        cpu: "50m"
    # Volume Mount
    volumeMount:
      enabled: false
    # Volume
    volume:
      enabled: false
      
    
# Service
service:
  # precise the differents ports to use for the application
  ports:
    first-port:
      name: first-port
      port: 30010
      targetPort: 8080

namespace: fleetman

# PVC
persistentVolumeClaim:
  enabled: true
  size: "1Gi"
  accessModes: ReadWriteMany
  storageClassName: standard
